// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/calculate": {
            "post": {
                "description": "Receives two operands and an operation and returns the result. Unary operations (squareRoot) use only operand1.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "calculator"
                ],
                "summary": "Calculate the result of an operation",
                "parameters": [
                    {
                        "description": "Operation and operands",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Request"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "invalid operation"
                }
            }
        },
        "model.Operation": {
            "type": "string",
            "enum": [
                "add",
                "subtract",
                "multiply",
                "divide",
                "exponent",
                "squareRoot",
                "percent"
            ],
            "x-enum-varnames": [
                "Add",
                "Subtract",
                "Multiply",
                "Divide",
                "Exponent",
                "SquareRoot",
                "Percent"
            ]
        },
        "model.Request": {
            "type": "object",
            "properties": {
                "operand1": {
                    "type": "number",
                    "example": 2
                },
                "operand2": {
                    "type": "number",
                    "example": 3
                },
                "operation": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/model.Operation"
                        }
                    ],
                    "example": "add"
                }
            }
        },
        "model.Response": {
            "type": "object",
            "properties": {
                "result": {
                    "type": "number",
                    "example": 5
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "Sezzle Calculator API",
	Description:      "Calculation API for the Sezzle calculator.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
